{
 "title": "K6 VictoriaMetrics",
 "tags": [
  "VictoriaMetrics",
  "k6"
 ],
 "time": { "from": "2025-07-10T18:35:22.718Z", "to": "2025-07-10T18:37:25.559Z" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "VU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "k6_vus_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP requests Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_Count_status_total_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Error http code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_Count_Error_total_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total response time > 2seg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_Count_Total_response_time_2s_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Dashboard ok",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by(name) (k6_check_status_200_total[$__interval])",
     "legendFormat": "200"
    },
    {
     "expr": "sum by(name) (k6_check_status_500_total[$__interval])",
     "legendFormat": "500"
    },
    {
     "expr": "sum by(name) (k6_check_status_503_total[$__interval])",
     "legendFormat": "503"
    },
    {
     "expr": "sum by(name) (k6_check_status_502_total[$__interval])",
     "legendFormat": "502"
    },
    {
     "expr": "sum by(name) (k6_check_status_504_total[$__interval])",
     "legendFormat": "504"
    },
    {
     "expr": "sum by(name) (k6_check_status_0_total[$__interval])",
     "legendFormat": "0"
    },
    {
     "expr": "sum by(name) (k6_check_status_99_total[$__interval])",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "HTTP Req Duration Summary OK",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "avg by(name) (k6_http_req_duration_avg)",
     "legendFormat": "avg"
    },
    {
     "expr": "avg by(name) (k6_http_req_duration_min)",
     "legendFormat": "min"
    },
    {
     "expr": "avg by(name) (k6_http_req_duration_max)",
     "legendFormat": "max"
    },
    {
     "expr": "avg by(name) (k6_http_req_duration_p95)",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by(name) (k6_http_req_duration_p99)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(name)({__name__=~\"k6_check_sla_fail_.*_total\"})",
     "legendFormat": "EndPoint"
    }
   ]
  },
  {
   "title": "Errores en response body",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(name) ({__name__=~\"k6_check_body_fail_.*_total\"})",
     "legendFormat": "EndPoint"
    }
   ]
  },
  {
   "title": "p95 (avg) por recurso(Time)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(name) (k6_http_req_duration_p95[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Requests (RPS) ok",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(k6_http_reqs_total[$__interval]))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(k6_http_reqs_total)[$__interval])",
     "legendFormat": "Total rps"
    }
   ]
  },
  {
   "title": "HTTP Req Duration Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    { "expr": "k6_http_req_duration_avg", "legendFormat": "avg" },
    { "expr": "k6_http_req_duration_min", "legendFormat": "min" },
    { "expr": "k6_http_req_duration_max", "legendFormat": "max" },
    { "expr": "k6_http_req_duration_p95", "legendFormat": "p95" },
    { "expr": "k6_http_req_duration_p99", "legendFormat": "p99" }
   ]
  },
  {
   "title": "avg_over_tim Promedio de Duración de Solicitudes (p95):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(k6_http_req_duration_p95{name=~\".*\"}[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}